# Generated by Django 4.1.7 on 2023-07-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_options_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('Importer', 'Importer'), ('Dealer_admin', 'Dealer admin'), ('Dealer_sales', 'Dealer sales'), ('Dealer_work_reciever', 'Dealer work reciever'), ('Dealer_mechanic', 'Dealer mechanic'), ('Vehicle_owner', 'Vehicle owner')], default='user', max_length=150),
        ),
    ]
