# Generated by Django 4.1.7 on 2023-07-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_options_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Driver', ' Driver'), ('user', 'user')], default='user', max_length=150),
        ),
    ]
