# Generated by Django 4.1.7 on 2023-07-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Driver', ' Driver'), ('user', 'user')], default='Driver', max_length=150),
        ),
    ]
