# Generated by Django 4.1.7 on 2023-09-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_user_is_deleted_user_is_registered"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Driver", "verbose_name_plural": "Driver"},
        ),
    ]
