# Generated by Django 4.1.7 on 2023-09-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Driver Name"),
        ),
    ]
