# Generated by Django 4.1.7 on 2023-09-17 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('runsheets', '0010_alter_passenger_name_alter_runsheet1_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='signature_sheet1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Morning_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('Evening_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('signature', models.ImageField(upload_to='signature_sheet_images/')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('passenger_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runsheets.passenger')),
            ],
            options={
                'verbose_name': 'signature_sheet1',
                'verbose_name_plural': 'signature_sheet1',
            },
        ),
    ]
