# Generated by Django 4.1.7 on 2023-09-17 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runsheets', '0010_alter_passenger_name_alter_runsheet1_date_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signature_sheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignPassengerTosignature_sheet1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runsheets.passenger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Driver')),
            ],
            options={
                'verbose_name': 'Assign Passenger to signature_sheet1',
                'verbose_name_plural': 'Assign Passengers to signature_sheet1',
            },
        ),
    ]
