# Generated by Django 4.1.7 on 2023-09-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signature_sheet", "0002_assignpassengertosignature_sheet1"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignatureReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("account_name", models.CharField(max_length=255)),
                ("start_time", models.TimeField()),
                ("finish_time", models.TimeField()),
                ("trip_explanation", models.CharField(max_length=255)),
                ("start_point", models.CharField(max_length=255)),
                ("drop_point", models.CharField(max_length=255)),
                ("taxi_no", models.CharField(max_length=255)),
                ("dc_no", models.CharField(max_length=255)),
                ("passenger_name", models.CharField(max_length=255)),
                ("fare_meter", models.DecimalField(decimal_places=2, max_digits=10)),
                ("extras", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "signature",
                    models.ImageField(blank=True, null=True, upload_to="signatures/"),
                ),
            ],
        ),
    ]
