# Generated by Django 4.1.7 on 2023-10-06 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="dockets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("account_name", models.CharField(max_length=255)),
                ("start_time", models.TimeField()),
                ("finish_time", models.TimeField()),
                ("trip_explanation", models.CharField(max_length=255)),
                ("start_point", models.CharField(max_length=255)),
                ("drop_point", models.CharField(max_length=255)),
                ("taxi_no", models.CharField(max_length=255)),
                ("dc_no", models.CharField(max_length=255)),
                ("passenger_name", models.CharField(max_length=255)),
                ("fare_meter", models.DecimalField(decimal_places=2, max_digits=10)),
                ("extras", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "signature",
                    models.ImageField(blank=True, null=True, upload_to="signatures/"),
                ),
                (
                    "docket_id",
                    models.CharField(
                        max_length=6, unique=True, verbose_name="Docket ID"
                    ),
                ),
                (
                    "Driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Driver",
                    ),
                ),
            ],
        ),
    ]
