# Generated by Django 4.1.7 on 2023-10-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Docket", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dockets",
            name="account_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="dockets",
            name="trip_explanation",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
