# Generated by Django 4.1.7 on 2023-07-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runsheets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='driver',
            new_name='User',
        ),
    ]
