# Generated by Django 4.1.7 on 2023-07-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runsheets', '0002_rename_driver_passenger_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='User',
            new_name='user',
        ),
    ]
