# Generated by Django 4.1.7 on 2023-07-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runsheets", "0003_rename_user_passenger_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Runsheet1Proxy",
            fields=[],
            options={
                "verbose_name": "Assign Passengers",
                "verbose_name_plural": "Assign Passengers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("runsheets.runsheet1",),
        ),
        migrations.AlterModelOptions(
            name="runsheet1",
            options={"verbose_name": "Runsheet1", "verbose_name_plural": "Runsheet1"},
        ),
        migrations.AlterField(
            model_name="runsheet1",
            name="Evening_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="runsheet1",
            name="Morning_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
