# Generated by Django 4.1.7 on 2023-07-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runsheets", "0004_runsheet1proxy_alter_runsheet1_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passenger",
            name="user",
        ),
    ]
