# Generated by Django 4.1.7 on 2023-07-31 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("runsheets", "0005_remove_passenger_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignPassengerToRunsheet1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Assign Passenger to Runsheet 1",
                "verbose_name_plural": "Assign Passengers to Runsheet 1",
            },
        ),
        migrations.CreateModel(
            name="HelpAndDispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complaint", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Runsheet1Proxy",
        ),
        migrations.AddField(
            model_name="passenger",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignpassengertorunsheet1",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="runsheets.passenger"
            ),
        ),
        migrations.AddField(
            model_name="assignpassengertorunsheet1",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
