# Generated by Django 4.1.7 on 2023-08-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runsheets", "0006_assignpassengertorunsheet1_helpanddispute_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passenger",
            name="user",
        ),
    ]
