# Generated by Django 4.1.7 on 2023-09-12 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "runsheets",
            "0008_runsheet8_runsheet7_runsheet6_runsheet5_runsheet4_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignpassengertorunsheet1",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet2",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet3",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet4",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet5",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet6",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet7",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet8",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Driver",
            ),
        ),
    ]
