# Generated by Django 4.1.7 on 2023-09-13 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("runsheets", "0009_alter_assignpassengertorunsheet1_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Passenger Name"),
        ),
        migrations.AlterField(
            model_name="runsheet1",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
