# Generated by Django 4.1.7 on 2024-07-18 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("runsheets", "0010_alter_passenger_name_alter_runsheet1_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignpassengertorunsheet1",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="runsheets.passenger"
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet1",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet2",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="runsheets.passenger"
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet2",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet3",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="runsheets.passenger"
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet3",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet4",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="runsheets.passenger"
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet4",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet5",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="runsheets.passenger"
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet5",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet6",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="runsheets.passenger"
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet6",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet7",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="runsheets.passenger"
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet7",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Driver",
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet8",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="runsheets.passenger"
            ),
        ),
        migrations.AlterField(
            model_name="assignpassengertorunsheet8",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Driver",
            ),
        ),
    ]
