# Generated by Django 4.2.4 on 2024-08-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runsheets', '0011_alter_assignpassengertorunsheet1_passenger_and_more'),
        ('runsheets', '0011_auto_20240718_1254'),
    ]

    operations = [
    ]
