# Generated by Django 4.2.4 on 2024-08-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runsheets', '0012_merge_20240819_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='runsheet1',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='runsheet2',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='runsheet3',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='runsheet4',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='runsheet5',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='runsheet6',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='runsheet7',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='runsheet8',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
